[ 2025-02-08 16:40:50,306 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.17:5000
[ 2025-02-08 16:40:50,307 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-02-08 16:41:00,043 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Feb/2025 16:41:00] "GET / HTTP/1.1" 200 -
[ 2025-02-08 16:41:09,596 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Feb/2025 16:41:09] "[31m[1mPOST /get_weather HTTP/1.1[0m" 415 -
[ 2025-02-08 16:41:12,735 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Feb/2025 16:41:12] "[31m[1mPOST /get_weather HTTP/1.1[0m" 415 -
[ 2025-02-08 16:41:23,196 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Feb/2025 16:41:23] "[31m[1mPOST /get_weather HTTP/1.1[0m" 415 -
[ 2025-02-08 16:41:24,481 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Feb/2025 16:41:24] "[31m[1mPOST /get_weather HTTP/1.1[0m" 415 -
[ 2025-02-08 16:41:50,858 ] 875 app - ERROR - Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\app.py", line 44, in index
    city = request.form['city']
           ~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 238, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\E15\Desktop\Workshop Project\app.py", line 69, in index
    raise CustomException(e, sys)
src.exception.CustomException: Error occurred in python script name [C:\Users\E15\Desktop\Workshop Project\app.py] line number [44] error message[400 Bad Request: The browser (or proxy) sent a request that this server could not understand.]
[ 2025-02-08 16:41:50,867 ] 97 werkzeug - INFO - 127.0.0.1 - - [08/Feb/2025 16:41:50] "[35m[1mPOST / HTTP/1.1[0m" 500 -
